version: "2.4"

volumes:
  mysql-data: {}  
  mysql-backups-data: {}

services:
  mysql:
    image: mysql:8
    volumes:
      - "./test/testdb-init.sql:/docker-entrypoint-initdb.d/testdb-init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=my-secret-pw --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 100

  automysqlbackup:
    build: .
    volumes:      
      - "mysql-backups-data:/backup"
    environment:
      USERNAME: root
      PASSWORD: "my-secret-pw"
      DBHOST: mysql
      DBEXCLUDE: "performance_schema information_schema"
      IGNORE_TABLES: "testdb.ignoretable"
      EXTRA_OPTS: "--single-transaction"
      CRON_SCHEDULE: "0 0 * * *"
    depends_on:
      mysql:
        condition: service_healthy 
    command: bash -c "rm -rf /backup/* && automysqlbackup"

  sut:
    build: ./test
    volumes:      
      - "mysql-backups-data:/backup"
    depends_on:
      - automysqlbackup
    command: bash -c "wait_to_finish.sh automysqlbackup && bats /usr/local/bin/automysqlbackup.bats"