version: "2.4"

volumes:
  mysql-data: {}  
  mysql-backups-data: {}

services:
  mysql:
    image: mysql:8
    volumes:
      - "./testdb-init.sql:/docker-entrypoint-initdb.d/testdb-init.sql"
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=my-secret-pw --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 100

  sut:
    build: .
    volumes:      
      - "mysql-backups-data:/backup"
    environment:
      USERNAME: root
      PASSWORD: "my-secret-pw"
      DBHOST: mysql
      DBEXCLUDE: "performance_schema information_schema"
      EXTRA_OPTS: "--single-transaction"
      CRON_SCHEDULE: "0 0 * * *"
    depends_on:
      mysql:
        condition: service_healthy 
    command: run_tests.sh